### ISSUE TITLE
Unstable builds @ travis-ci 

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/test-automation-framework#24]
I'll give [CircleCI](https://circleci.com/) a try.

**Comment by MarkusTiede** [comment]
Same problem as on Travis 

`[ERROR] Failed to execute goal on project taf-robot: Could not resolve dependencies for project com.baloise.testing.framework:taf-robot:jar:0.0.8-SNAPSHOT: Failed to collect dependencies at com.sikulix:sikulixapi:jar:1.1.0 -> jxgrabkey:jxgrabkey:jar:1.0: Failed to read artifact descriptor for jxgrabkey:jxgrabkey:jar:1.0: Could not transfer artifact jxgrabkey:jxgrabkey:pom:1.0 from/to uni-due.de (http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/): Connect to mvn.is.inf.uni-due.de:8081 [mvn.is.inf.uni-due.de/134.91.35.230] failed: Connection refused (Connection refused) -> `

**Comment by nagarjunay** [comment]
Sikuli dependencies not working 

Failed to collect dependencies at com.sikulix:sikulixapi:jar:1.1.0 -> jxgrabkey:jxgrabkey:jar:1.0: Failed to read artifact descriptor for jxgrabkey:jxgrabkey:jar:1.0: Could not transfer artifact jxgrabkey:jxgrabkey:pom:1.0 from/to uni-due.de (http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/): Transfer failed for http://mvn.is.inf.uni-due.de:8081/nexus/content/repositories/atunes-dependencies/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom: Connect to mvn.is.inf.uni-due.de:8081 [mvn.is.inf.uni-due.de/134.91.35.230] failed: Connection timed out: connect -> [Help 1]

**Comment by MarkusTiede** [comment]
Hi @nagarjunay - are you sure that you're using the most recent master version? Sikuli has been remove a while ago:

E.g. `mvn clean verify dependency:tree | grep sikulix` does not show this depency anymore.

Could you please check whether this is also present in the most recent version(s)?
